# Generated by Django 3.2.5 on 2022-01-09 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_teams_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='googlep_link',
            new_name='google_plus_link',
        ),
    ]
