# Generated by Django 4.0.1 on 2022-01-10 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_rename_googlep_link_team_google_plus_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='fb_link',
            new_name='facebook_link',
        ),
    ]
